# Generated by Django 3.2.8 on 2021-12-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_comment_id'),
        ('Profile', '0010_auto_20211115_2326'),
        ('Comment', '0004_auto_20211204_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
