# Generated by Django 3.2.8 on 2021-10-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('New order', 'New order'), ('Order processing', 'Order processing'), ('Finished', 'Finished')], default='New order', max_length=100)),
            ],
        ),
    ]
