# Generated by Django 3.2.7 on 2021-11-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='amount_of_products',
            new_name='amount_of_items',
        ),
    ]
