# Generated by Django 3.2.7 on 2021-12-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
        ('Profile', '0010_auto_20211115_2326'),
        ('Order', '0004_rename_amount_of_products_orderitem_amount_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comment.comment'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
    ]
