# Generated by Django 3.2.8 on 2021-12-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_comments'),
        ('Order', '0005_auto_20211204_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comment.comments'),
        ),
    ]
