# Generated by Django 3.2.8 on 2021-10-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20211026_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_id',
            new_name='id',
        ),
    ]
